# fly.toml app configuration file generated for braidnet on 2023-06-06T17:14:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "braidnet"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
  strategy = "immediate"

[env]
  LOG_LEVEL = "debug"
  BRAIDNET_API_PORT = "9090"

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[services]]
  internal_port = 4369
  protocol = "tcp"

  [[services.ports]]
      port = 4369

[[services]]
  internal_port = 50000
  protocol = "tcp"

  [[services.ports]]
      port = 50000

[[services]]
  internal_port = 50100
  protocol = "tcp"

  [[services.ports]]
      port = 50100

[checks]
  [checks.healthcheck]
    grace_period = "10s"
    interval = "5s"
    method = "get"
    path = "/hc"
    port = 9080
    timeout = "2s"
    type = "http"
