# fly.toml app configuration file generated for braidnet on 2023-06-06T17:14:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "braidnet"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  LOG_LEVEL = "debug"
  ORIGIN = "braidnet.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
